/**
 * Auth service — JWT token generation/verification + password hashing.
 *
 * Password hashing strategy:
 *   - NEW passwords → Argon2id (OWASP-recommended, GPU/ASIC resistant)
 *   - EXISTING bcrypt hashes → still verified via bcrypt, then auto-upgraded
 *     to Argon2id on next successful login (transparent migration)
 *
 * Argon2id parameters (OWASP 2024 recommended):
 *   - Memory:      64 MiB  (65536 KiB)
 *   - Iterations:  3        (time cost)
 *   - Parallelism: 4        (threads)
 *   - Salt:        16 bytes (auto-generated by argon2)
 *   - Hash length: 32 bytes
 */
const jwt = require('jsonwebtoken');
const argon2 = require('argon2');
const bcrypt = require('bcryptjs'); // kept for backward compat
const crypto = require('crypto');
const env = require('../config/env');

// ── Argon2id configuration (OWASP recommended) ────────────────────────
const ARGON2_OPTIONS = {
  type: argon2.argon2id,      // Hybrid: side-channel + GPU resistant
  memoryCost: 65536,          // 64 MiB
  timeCost: 3,                // 3 iterations
  parallelism: 4,             // 4 threads
  hashLength: 32,             // 32-byte output
};

// ── Password hashing ──────────────────────────────────────────────────
/**
 * Hash a password using Argon2id.
 * Output format: $argon2id$v=19$m=65536,t=3,p=4$<salt>$<hash>
 * Salt is auto-generated (16 bytes).
 */
async function hashPassword(plain) {
  return argon2.hash(plain, ARGON2_OPTIONS);
}

/**
 * Verify a password against a stored hash.
 * Supports both Argon2id and legacy bcrypt hashes.
 *
 * @returns {{ valid: boolean, needsRehash: boolean }}
 *   - valid: true if password matches
 *   - needsRehash: true if the hash is bcrypt (should be upgraded to argon2)
 */
async function comparePassword(plain, storedHash) {
  // Detect hash type by prefix
  if (storedHash.startsWith('$argon2')) {
    // Argon2id hash
    const valid = await argon2.verify(storedHash, plain);
    // Also check if argon2 params have changed and need re-hash
    const needsRehash = valid && argon2.needsRehash(storedHash, ARGON2_OPTIONS);
    return { valid, needsRehash };
  }

  if (storedHash.startsWith('$2a$') || storedHash.startsWith('$2b$')) {
    // Legacy bcrypt hash — verify, then flag for rehash
    const valid = await bcrypt.compare(plain, storedHash);
    return { valid, needsRehash: valid }; // Always rehash bcrypt → argon2
  }

  // Unknown format
  return { valid: false, needsRehash: false };
}

// ── JWT tokens ─────────────────────────────────────────────────────────
function generateAccessToken(user) {
  return jwt.sign(
    { id: user.id, email: user.email, role: user.role },
    env.JWT_ACCESS_SECRET,
    { expiresIn: env.JWT_ACCESS_EXPIRY }
  );
}

function generateRefreshToken(user) {
  return jwt.sign(
    { id: user.id, type: 'refresh' },
    env.JWT_REFRESH_SECRET,
    { expiresIn: env.JWT_REFRESH_EXPIRY }
  );
}

function verifyAccessToken(token) {
  return jwt.verify(token, env.JWT_ACCESS_SECRET);
}

function verifyRefreshToken(token) {
  return jwt.verify(token, env.JWT_REFRESH_SECRET);
}

// ── Token hashing (for DB storage) ─────────────────────────────────────
function hashToken(token) {
  return crypto.createHash('sha256').update(token).digest('hex');
}

// ── Password reset token ───────────────────────────────────────────────
function generateResetToken() {
  const token = crypto.randomBytes(32).toString('hex');
  const hash = crypto.createHash('sha256').update(token).digest('hex');
  // Token expires in 1 hour
  const expiresAt = new Date(Date.now() + 60 * 60 * 1000);
  return { token, hash, expiresAt };
}

module.exports = {
  hashPassword,
  comparePassword,
  generateAccessToken,
  generateRefreshToken,
  verifyAccessToken,
  verifyRefreshToken,
  hashToken,
  generateResetToken,
};
